### ISSUE TITLE
DHO My Profile - Personal Info Widget

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#212]
**Summary:**
As a DHO user I would like to see my personal info displayed on my profile page so I can see it on one glance.

**Description:**
URL: https://dho.hypha.earth/#/@accountname

**Acceptance Criteria:**

The following items should be displayed:

Picture & Name
- [x] User Avatar 
- [x] User Name
- [x] Blockchain Name
- [x] Tags (currently added in profile info but not clickable - should be used as filters later to find users with specific skills)

Info
- [x] H Voice
- [x] City, Country (Time Zone) e.g. Santa Teresa, Costa Rica (UTC-06:00) 
- [x] Date the user joined Hypha (m d, yy)

How to reach me
- [ ] Copy: "How to reach me" (Here only the channels are displayed that the user sets in the "settings")
- [ ] Discord Channel #1234
- [ ] Telegram Link
- [ ] E-Mail
- [ ] Phone

Edit icon
- [ ] Edit icon (pen) in top right corner (the user should be able to edit the info here right away. When he clicks the edit icon a overlay will open where he can adjust the settings. Link to story: **to be done** 

**Ressources:**

Attachement: 
Designs

Responsive Designs:
**To be done** 

<img width="643" alt="Screenshot 2021-03-19 at 16 31 19" src="https://user-images.githubusercontent.com/75991832/111848417-9cca2280-88d0-11eb-8ce4-3b5941117e5e.png">
