### ISSUE TITLE
DHO My Profile - About Widget

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#213]
**Summary:**
As a DHO user I would like to see my bio displayed on my profile page so I can see it on one glance.

**Description:**
URL: https://dho.hypha.earth/#/@accountname

**Acceptance Criteria:**

The following items should be displayed:

- [ ] Headline: "About Username" e.g. About Hypha Member 123
- [ ] Paragraph about the user that he / she can add in the settings (link to settings story: to be done)
- [ ] Edit icon (pen) in top right corner (the user should be able to edit the info here right away. When he clicks the edit icon a overlay will open where he can adjust the settings. Link to story: **to be done** 

**Ressources:**

Attachement: 
Designs

Responsive Designs:
**To be done** 

<img width="645" alt="Screenshot 2021-03-19 at 16 32 32" src="https://user-images.githubusercontent.com/75991832/111848489-c125ff00-88d0-11eb-81cc-17f7f63b4a6d.png">

**Comment by lukegravitt** [comment]
Our current profile 'about' details supports markdown, so many of the profiles we have on the backend have some markdown in them. If we don't want to support markdown, we can trim it in the client I think, but it might be something certain members want. Need guidance here.

**Comment by leonieherma1** [comment]
Hey @lukegravitt the idea is to have a separate edit screen in a overlay where the user can change all settings. When you click "edit" in the about component you get to that screen: 

![image](https://user-images.githubusercontent.com/75991832/112385410-34ef4f80-8cb5-11eb-9073-fe1d4e7b6fa6.png)


Here we can add the markup (if that is possible and wanted)
