### ISSUE TITLE
DHO Other Member Profile - Personal Info Widget

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#219]
**Summary:**
As a DHO user I would like to see other member's personal info displayed on their profile page so I can see it on one glance.

**Description:**
URL: https://dho.hypha.earth/#/@accountname

**Acceptance Criteria:**

The following items should be displayed:

Picture & Name
- [x] User Avatar of member
- [x] User Name of member
- [x] Blockchain Name of member
- [x] Tags (currently added in profile info but not clickable - should be used as filters later to find users with specific skills)

Info
- [x] H Voice
- [x] City, Country (Time Zone) e.g. Santa Teresa, Costa Rica (UTC-06:00) 
- [x] Date the user joined Hypha (m d, yy)

How to reach me
- [ ] Copy: "How to reach me" (Here only the channels are displayed that the user sets in the "settings")
- [ ] Discord Channel #1234
- [ ] Telegram Link
- [ ] E-Mail
- [ ] Phone

Connect:
- [ ] Connect Button
- [ ] When the User are already connected the Button changes it Design and says "disconnect"

_Caution: no edit icon here since I should not be able to edit someone else's profile. I only see the edit icon on my own profile page_

**Ressources:**

Attachement: 
Wireframes

Final Designs:
**To be done** 

![DHO Other Member Profile - Personal Info Widget](https://user-images.githubusercontent.com/75991832/102699323-5863b380-4209-11eb-9038-7abb8c5d1f07.jpeg)
