### ISSUE TITLE
DHO My Profile - My Organizations Widget (S)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#268]
**Summary:**
As a DHO user I would like to see my organizatons / dhos that I am member of displayed on my profile page so I can see it on one glance.

**Description:**
URL: https://dho.hypha.earth/#/@accountname

**Acceptance Criteria:**

The following items should be displayed:

- [x] Titel
- [ ] Logo of Organization
- [x] Name of Organization

Action: When I click on the organization (little arrow) I go to the other DHO

Edit icon
- [x] no edit icon

**Ressources:**

Attachement: 
Designs

https://xd.adobe.com/view/500c58dc-9103-41f4-a82a-bb390323fbd8-055f/screen/5b42abf5-afa8-4070-8b75-e534f474139f

Responsive Designs:
**To be done**

**Comment by leonieherma1** [comment]
@arsenijesavic I got a bit of feedback from our designer regarding this widget. Overall it's great but could you double check the following:
- the spacing below the headline
- the spacing between the individual organizations
- remove hover from "see more Button" and from organization links
- Add little grey arrow next to organization name
- Add "1 active assignment" below title (only if you have that data easily, if not we can leave it out for MVP)

Here is the design again, please double check the spacing in the "code" tab in XD
https://xd.adobe.com/view/2e6dc275-76dc-4722-a922-cc60c5d7d653-7b3e/screen/c67400d5-b48c-4257-9233-5501d710bbf9/

**Comment by leonieherma1** [comment]
@arsenijesavic I just saw the link for the design was not updated - my bad, so sorry for that! We have a new universal link where you find all updated designs for MVP. https://xd.adobe.com/view/0d46ebe4-2b4b-437b-86f7-c3c5c18e05ac-5815/?fullscreen&hints=off So please follow this "MVP" Design in every story. I will also update the missing stories with the correct link!
