### ISSUE TITLE
DHO My Profile - My Wallet Widget

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#269]
**Summary:**
As a DHO user I would like to see my wallet info (HVOICE, HUSD, HYPHA & SEEDS) info displayed on my profile page so I can see it on one glance.

**Description:**
URL: https://dho.hypha.earth/#/@accountname

**Acceptance Criteria:**

The following items should be displayed:

- [x] Headline (My Wallet)
- [x] Logo of Token / Currency
- [x] Amount of Token / Currency
- [ ] Little Arrow Up if I have a higher amount than after my last login (e.g. got paid) and number displayed in green
- [x] HVOICE: Total HVOICE and % of HVOICE (info tooltip: This is the percentage of your HVOICE compared to all members of this organization)
- [x] HUSD: little plus icon - opens a form to redeem USD or buy SEEDS right away

Action
- [x] When I click on the widget I get to /wallet

Edit icon
- [ ] not edit icon here

**Ressources:**

Attachement: 
Designs

Responsive Designs:
**To be done** 

<img width="643" alt="Screenshot 2021-03-19 at 16 30 14" src="https://user-images.githubusercontent.com/75991832/111848349-76a48280-88d0-11eb-81d7-0913761c45e6.png">

<img width="557" alt="Screenshot 2021-03-19 at 16 33 44" src="https://user-images.githubusercontent.com/75991832/111848547-eb77bc80-88d0-11eb-95fc-91a958e1f1cb.png">
