### ISSUE TITLE
New Profile - Overview

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#323]
**Summary:**
As a DHO user I would like to see the new widget based ui design for my profile.

**Description:**
URL: https://dho.hypha.earth/#/@accountname

**Acceptance Criteria:**

New features:

Personal Info Widget: (https://github.com/hypha-dao/dho-web-client/issues/212) 
- [ ]all the data in their profile yet e.g. discord #, telegram, archetype) - We will update the setting screens later and add new fields for all the info

About Widget: (https://github.com/hypha-dao/dho-web-client/issues/213)
- [x] Bio already exists in profile

My Wallet Widget: (https://github.com/hypha-dao/dho-web-client/issues/269)
- [x] HVOICE: Total HVOICE and % of HVOICE (info tooltip: This is the percentage of your HVOICE compared to all members of this organization)
- [ ] only visible for me (not the other users)
- [x] HUSD: little plus icon - opens a form to redeem USD or buy SEEDS right away

My Organizations: (https://github.com/hypha-dao/dho-web-client/issues/268)
- [ ] link to the other DHOs that the user is member of (feature not available yet)

My voting history: (https://github.com/hypha-dao/dho-web-client/issues/217)
- [x] enhance current list with more details (vote yes or no, name of proposal, etc...)

My transaction history: (https://github.com/hypha-dao/dho-web-client/issues/218)
- [ ] not visible for other users (just myself)
- [ ] enhance with details e.g. assignment name

My open proposals: (https://github.com/hypha-dao/dho-web-client/issues/214)
- [ ] shows my open proposals

My active assignments: (https://github.com/hypha-dao/dho-web-client/issues/215)
- [x] shows all active assignments, that I currently have with an "active" label

[My achievement history: ](https://github.com/hypha-dao/dho-web-client/issues/216)
- [ ] shows all my assignments, badges, roles from the past with an "archived" label

Other member view: ](https://github.com/hypha-dao/dho-web-client/issues/219)
- [x] same widgets and view (except "my wallet", and "my transactions")
- [ ] add "connect" button 

Action
- [ ] Edit icon in all widgets link to profile settings (new settings screen - to be done)

New Card Layout Overview: https://github.com/hypha-dao/dho-web-client/issues/324

**Ressources:**

Attachement: 
Designs (XD)

Responsive Designs (to be done!)

![image](https://user-images.githubusercontent.com/75991832/111846241-ff6cef80-88cb-11eb-918f-1f8e428af156.png)
