### ISSUE TITLE
DHO New Card Layout - Contribution Proposal

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#326]
**Summary:**
As a DHO user I would like to see the new card layout for my contribution proposal card in order to be able to use the 5 scale voting (hell yeah).

**Description:**
URL: https://dho.hypha.earth/#

**Acceptance Criteria:**

Labels:
- [ ] Primary label for states of drafting & voting (orange) 
- [ ] Primary label for: passed (green) / not passed (red) when vote ended or quorum is reached
- [ ] Secondary small label (blue) for the state of "voting": new, updated, suspending
- [ ] Document type: e.g. CONTRIBUTION

Secondary Action:
- [ ] Ellipsis: edit, withdraw

Header Information:
- [ ] Avatar in a circle
- [ ] Name of user who proposed the contribution
- [ ] HVOICE (total number) and % of HVOICE in brackets behind that 
- [ ] Name of contribution (three lines)

Voting Section:
- [ ] Headline: "Votes endorsed by HVOICE"
- [ ] Voting bar with labels (In favor: X% and against: X%)
- [ ] Triangle to indicate votes needed to pass (e.g. 80%)
- [ ] Show orange triangle if the vote is controversial (overview of exact rules @sceenius ?)
- [ ] When the voting time ends, or quorum is reached the voting bar goes from light colours (50% opacity) to full colours 

Info Section:
- [ ] Headline: Info
- [ ] Date: Vote ends in X days / Vote ended X days ago (colour of dot changes from grey to green when voting period has ended)
- [ ] Quorum: 10,5% (20% needed) (colour of dot changes from grey to green when quorum is reached)

Primary Action:
- [ ] 5 Voting Buttons: Hell Yeah, Yes, Abstain, No, Hell No
- [ ] After the user casts his vote the button is slightly bigger and shows a white checkbox
- [ ] When the voting period on your own proposal has ended, the following two actions replace the voting buttons: "activate" or "archive" (then become states: "activated" or "archived".
- [ ] When the voting period on another persons proposal ended, the following shows: "X You voted against this proposal" or "V You voted in favor of this proposal"

Footer / Social Actions:
- [ ] Possibility to like the card & show amount of likes (when clicking on the likes the detail view of the card opens with a list of people that liked your proposal card)
- [ ] Possibility to comment & show amount of comments ((when clicking on the likes the detail view of the card opens with a list of people that liked your proposal card)
- [ ] Possibility to click on the link shows a message "link copied to clipboard" in order to share a direct link to proposal on e.g. discord

Action
- [ ] When I click on the card the new detail view opens - currently in the sidebar (will be redesigned soon - mockups attached)

Other Card States: (Active & Archived)
- [ ] similar to proposal card, except:
- [ ] Primary label "Active" (green) or "Archived" (grey)
- [ ] remove voting bar, info section & primary action (vote buttons)

**Ressources:**

Attachement: 
Contribution Proposal designs (cards)
Mockups (Detail View)

Responsive Designs:
**To be done** 

![image](https://user-images.githubusercontent.com/75991832/112003308-67971d80-8ae6-11eb-9aa9-05d6bbdb4bb8.png)
![Labels_Cards_1](https://user-images.githubusercontent.com/75991832/112003391-7bdb1a80-8ae6-11eb-9cfc-ec490981a838.png)
![Contribution](https://user-images.githubusercontent.com/75991832/112023213-a7670080-8af8-11eb-80f1-a0a9dd416668.png)
