### ISSUE TITLE
Add Circles as a dropdown to proposals

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#431]
**Summary:**
As a DHO user I would like to be able to chose the circle my proposal is sponsored by from a dropdown list while creating a proposal. 

**Acceptance Criteria:**

- [ ] find a way to show and connect document types to circles
- [ ] show circles as a dropdown when creating a new proposal
- [ ] show circle on assignment / contribution card in frontend

**Ressources**
Issue is connected to the bigger epic of "Accounting": https://github.com/hypha-dao/dho-web-client/issues/184

![image](https://user-images.githubusercontent.com/75991832/120723223-92123900-c48e-11eb-9ddf-df15c14a2267.png)

**Comment by leonieherma1** [comment]
@lukegravitt can I close this since the circle dropdown is part of this story: https://github.com/hypha-dao/dho-web-client/issues/504

Or prefer to have it separate?

**Comment by lukegravitt** [comment]
Let's close this one.
