### ISSUE TITLE
New Activities Page

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#448]
**Summary:**
As a DHO user I would like to see the information about current activities / projects in a new overview page.

**Description:**
URL: https://dho.hypha.earth/#/documents/assignment
https://dho.hypha.earth/#/documents/assignment

**Acceptance Criteria:**

Filter:

- [ ] Search
- [ ] Status: Active, Archived, Suspended
- [ ] Default Sort by Date: Descending, Ascending

Action
- [ ] When I click on the card the new detail view opens - currently sidebar (will be redesigned soon - mockups attached)

**Ressources:**

Attachement: 

https://xd.adobe.com/view/500c58dc-9103-41f4-a82a-bb390323fbd8-055f/screen/e9e03477-414f-44a3-bdea-efec1f5ce808

Responsive Designs:
**To be done**
