### ISSUE TITLE
About Hypha Dashboard

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#466]
**Summary:**
As a DHO user I would like to see the information about Hypha in one overview page so I can get the most relevant information quickly and navigate to detail pages from there.

**Description:**
old URL:  /#/dashboard
new URL: /hypha?

**Acceptance Criteria:**

- [ ] Preview of 5 Members (last joined?) and link "see XX more" to Members page with no filters selected
- [ ] Preview of 5 most recent assignments / contributions (last activated?) and link "see XX more" to /activity page with no filters preselected (do we have a /activity page?)
- [ ] Link to list of Archetypes list with no filters selected
- [ ] Link to Badges List with no filters preselected
- [ ] Finance Widget with link to finance / treasury burn rate chart for the whole organization
- [ ] Other widgets to be done?

**Ressources:**

Attachement: 

https://xd.adobe.com/view/500c58dc-9103-41f4-a82a-bb390323fbd8-055f/screen/ff6e962f-e898-4013-bc5f-1b8350cd0b05

Responsive Designs:
**To be done**

**Comment by lukegravitt** [comment]
I think we could merge DHO Work #469 and this page into a single page that represents what the org is and what it's doing. This page already serves as a link to the activity list (which I think is just the search results page with activity filtered -- something like /search/filter=passed)

**Comment by leonieherma1** [comment]
> I think we could merge DHO Work #469 and this page into a single page that represents what the org is and what it's doing. This page already serves as a link to the activity list (which I think is just the search results page with activity filtered -- something like /search/filter=passed)

Yeah I think this "About Hypha Dashboard" has a widget that shows the current 10 assignments that are active or so. But then you do need to be able to "click more" and go to the /activities or /work page. So https://github.com/hypha-dao/dho-web-client/issues/469 is that new page. What do you mean with search result page? Because I thought that members and proposals are separate pages, so that would be the current project / work page right?

**Comment by leonieherma1** [comment]
Closing this - new ticket combines DHO Work and About Hypha Dashboard: https://github.com/hypha-dao/dho-web-client/issues/531
