### ISSUE TITLE
Home / Dashboard

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#467]
**Summary:**
As a DHO user I would like to see the information about Hypha in one overview page so I can get the most relevant information quickly and navigate to detail pages from there.

**Description:**
old URL:  /#/dashboard
new URL: /hypha?

**Acceptance Criteria:**

- [ ] Preview of 5 Members (last joined?) and link "see XX more" to Members page with no filters selected
- [ ] Preview of 5 most recent open proposals (last added?) and link "see XX more" to /proposals page with no filters preselected (do we have a /activity page?)
- [ ] Link to Documentation
- [ ] Link to Badges List with no filters preselected
- [ ] Finance Widget with link to finance / treasury burn rate chart for the whole organization
- [ ] Other widgets to be done?

**Ressources:**

Attachement: 

https://xd.adobe.com/view/500c58dc-9103-41f4-a82a-bb390323fbd8-055f/screen/ff6e962f-e898-4013-bc5f-1b8350cd0b05

Responsive Designs:
**To be done**
