### ISSUE TITLE
DHO Work (active projects)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#469]
**Summary:**
As a DHO user I would like to see a list of all current projects that are happening in the DHO to get an overview of what the organization is doing and if it is following its purpose.

**Description:**

old URL:
/#/documents/badge
/#/documents/role
/#/documents/assignment

new URL:
/activity

**Acceptance Criteria:**

- [ ] List / Card View switcher
- [ ] Title: Activity / Current Projects (to be done)

List / Card View of active assignments with the following elements:

- [ ] Label for document type
- [ ] Label for Circle
- [ ] Titele
- [ ] Username
- [ ] Total compensation equiv. USD
- [ ] Date

Filter:

- [ ] Search (Free Text Search)
- [ ] Type: Contribution, Role Archetype, Assignment, Quest, Badge, Badge Assignment (Toggle)
- [ ] Circle: List of circles (Dropdown Multiple Select)
- [ ] Sort by Archetype (not possible for contributions?) (Multiple Select Dropdown)
- [ ] Sort by Start Date (Ascending / Descending)

Action
- [ ] When I click on the card the user goes to the detail view page.

Sorting:
- [ ]sort by newest activated assignemnts / contributions

**Ressources:**

Attachement: 

https://xd.adobe.com/view/500c58dc-9103-41f4-a82a-bb390323fbd8-055f/screen/c20e1ce9-f9cf-4900-b68a-9bf9f9828c3e

Responsive Designs:
**To be done**

**Comment by lukegravitt** [comment]
We need a detail page for these too fyi :)

**Comment by leonieherma1** [comment]
> We need a detail page for these too fyi -- it's probably the same -ish structure to proposal page, but there are some differences.

Yes, it's on my list. I also. thought it is the same with some minor changes (e.g. instead of vote button it says: you voted yes) etc...
