### ISSUE TITLE
DHO Settings Screen (L)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#470]
**Summary:**
As a new DHO user I would like to be able to configure certain settings on an "admin configuration screen". The first iteration should only show the values that are absolutely needed in order to set up a new DHO. The optional settings can be seen as kind of "addons" (e.g. Salary Bands)

Artboard – 1.pdf

**Description:**

old URL: doesn't exist

new URL:
/treasury

**Acceptance Criteria:**

Design:
- [ ] Change colour scheme
- [ ] Change logo
- [ ] Change Title and purpose (description on dashboard)
- [ ] Change link to the docs

Salary Bands:
- [ ] is it deletable? (what happens to current roles? Maybe when you can't have any roles with that salary band)

Token:
- [ ] Disable / Enable preconfigured Token (Peg Token, Voice Token, SEEDS Token)

**Design**
