### ISSUE TITLE
Hide extend button while "extended assignment" is up vor voting

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#472]
**Summary:**
As a DHO user I would not like to see the "extend" button on my current proposal, if I already clicked "extend" and proposed my extension, so I don't get confused and think that I need to extend again.

**Description:**

**Acceptance Criteria:**

- [ ] check if extend button was already pressed 
- [ ] check if extended proposal is published
- [ ] when published "hide" the extend button until the assignment expires

**Ressources:**
