### ISSUE TITLE
Active Project Detail Page

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#474]
**Summary:**
As a DHO user I would like to see all details of an active assignment / contribution in one page.

**Description:**

old URL:
sidebar

new URL:
/activity/<uuid>

**Acceptance Criteria:**

- [ ] back button
- [ ] Title: Project Title

Payout Widget:
- [ ] Title: Payout
- [ ] Dropdown: Totals (default), Cycle, Periods
- [ ] 1.Token Icon, Token Name, Value
- [ ] 2.Token Icon, Token Name, Value
- [ ] 3.Token Icon, Token Name, Value

Duration Widget:
- [ ] Calendar Icon
- [ ] Start Date - End Date (e.g. June 2, 2021 - Sep 4, 2021)
- [ ] #amount of periods (e.g. #12 periods)

Member:
- [ ] Username
- [ ] Profile Photo
- [ ] HVOICE (or Badges)?

Proposal Detail Widget:
- [ ] Label: Document Type
- [ ] Label: Circle
- [ ] Titel of Proposal
- [ ] Text field with Objectives, Key Results, etc...
- [ ] Button to see link with full documentation (if it exists)

Vote Widget:
- [ ] Title: Vote
- [ ] Unity & Quorum
- [ ] Instead of vote button, show: "You voted XX"

Last Votes Widget:
- [ ] date
- [ ] name
- [ ] vote (yes, no, support, abstain, harmful, unicorns, etc...)
- [ ] % of vote (of HVOICE in organisation - not per this vote (current status)

Comment Widget:
- [ ] not MVP see different story: #456 

**Ressources:**

Attachement: 

https://xd.adobe.com/view/500c58dc-9103-41f4-a82a-bb390323fbd8-055f/screen/149661be-9415-4323-89df-77d0b605b9be

Responsive Designs:
**To be done**

**Comment by leonieherma1** [comment]
@jmgayosso @DaniPoot 
Voting widget looks very different from design, please fix.
<img width="236" alt="image" src="https://user-images.githubusercontent.com/75991832/157362963-e66b83fe-5ab7-40ef-bcc3-774a1c6698b2.png">
<img width="343" alt="image" src="https://user-images.githubusercontent.com/75991832/157362977-3ab1193a-db72-4b4a-88cd-8e3f63f3e4aa.png">



Or @pugakn is this something you will fix with the generic design (e.g. voting "yes" "no" in one line with name and avatar, number "1" of pages not blue, etc...)
