### ISSUE TITLE
Like function proposals

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#489]
Summary:
As a DHO user I would like to be able to like a proposal to show my support. 

Description:

- [ ] Add a "like" button inside the proposal detail view page
- [ ] Show the total amount of likes on the proposal detail view page and preview card
- [ ] User can like and remove their like 
- [ ] There is no option for "dislike" or "downvote"
- [ ] Like should be a thumbs up or heart (to decide with Massimo)

Design:
to be done

**Comment by josejulio** [comment]
The proposal is the one that has the like? So IIUC this is not related to the comments (comments having a like).

I think it might be possible to include this as part of the `comments` contract (maybe a better name is required for that contract :sweat_smile:)

**Comment by leonieherma1** [comment]
Yes the proposal is the one that get likes. I think it should also be possible to like a comment. But it's pretty much two features:

1. Like the whole proposal
2. Like an individual comment with an emoticon (same as discord for example) as part of the comment feature
