### ISSUE TITLE
DHO Creation Wizard Flow - Step 1

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#507]
**Summary**
As a DHO user I would like to be able to create a new DHO with a few easy steps.

**Description:**
For the Beta Version we create DHOs manually via a command line and create the settings manually. For the public version we would like to have a "DHO Creation Wizard" that has 6 steps.

**Acceptance Criteria**

Step 1:

- [x] Headline: General Info
- [x] Copy: to be done
- [x] Name Field (max 50 characters)
- [x] Description Field (max 300 characters)
- [x] Button: Next Step

**Design**
https://xd.adobe.com/view/27bc7fff-1845-449c-913a-4ecfb3c9461c-72ef/screen/c0b2078b-7a17-4c4f-9004-c8dd57d4c273/
