### ISSUE TITLE
DHOscovery Flow - Cards / List [S]

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#508]
**Summary:**
As a user I would like to be able to easily find new DHOs so I can find out more information about them and possibly apply to become a member. 

Acceptance Criteria:

- [ ] "World Icon" 

DHO Cards:
- [ ] Add screen that shows different DHOs as cards 
- [ ] Add header image of DHO
- [ ] Add "share" icon - copies link ("link was copied to clipboard" message)
- [ ] Add Title of DHO and description
- [ ] Add Date Joined + icon
- [ ] Add number of members + icon
- [ ] Add number of active projects 
- [ ] Cards are displayed in an infinite scroll list / or pagination?

**Designs**

https://xd.adobe.com/view/4c39d655-0dd3-4e0c-b4f2-f5363b3205f5-196a/screen/2387d59a-e7ac-4d05-83eb-5d277ffd3050/

![image](https://user-images.githubusercontent.com/75991832/143137277-23c5ce38-b1c5-4757-a3fd-a297a8725829.png)
