### ISSUE TITLE
Organisational Page - Header & Quick Links

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#531]
**Summary:**
As a DHO user I would like to see an overview page about the Hypha Organization with links to organisational pages (e.g. treasury, archetypes, all projects, etc...) in order to understand the organisation better and navigate to pages with more info. 

**Description:**

old URL:

new URL:
/organization?

**Acceptance Criteria:**

- [ ] Headline: The Purpose of %%DHO Name%%
- [ ] Copy: to be provided by the respective DHO (For Hypha see: https://docs.google.com/document/d/1KHC_6Cha8MC2NMKDV6XRXKuZGS7kPdVGuLtF_kSYvbU/edit)

Quick Links:

- [ ] Headline: Quick LInks
- [ ] Link 1: Badges (link to /badges)
- [ ] Link 2: Archetypes (link to /archetypes)
- [ ] Link 3: Treasury (link to /treasury)

_- should the links be /organization/badges or simply /badges?_

**Ressources:**

Attachement: 

![unknown](https://user-images.githubusercontent.com/75991832/135150127-f39ae2f3-4773-44ab-a848-0485b7addf58.png)

Responsive Designs:
**To be done**
