### ISSUE TITLE
Account Creation - Step 1 (Picture, Name, Location)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#593]
**Summary:**
As a new user I would like to be able to create a profile inside the DHO.

**Acceptance Criteria:**
- [ ] Upload profile picture
- [ ] Name Text Field
- [ ] Nickname (automatically generated)
- [ ] Location Dropdown
- [ ] Time Zone Dropdown
- [ ] Next Button

**Design:**
https://xd.adobe.com/view/27bc7fff-1845-449c-913a-4ecfb3c9461c-72ef/screen/1dda7bde-a1b6-4cb0-898e-1cadba366796
