### ISSUE TITLE
Account Creation - Step 4 (Contact Info)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#594]
**Summary:**
As a new user I would like to be able to create a profile inside the DHO.

**Acceptance Criteria:**
- [ ] Headline
- [ ] Description Copy
- [ ] Phone icon, Phone Number Field, Toggle to make phone preferred contact method
- [ ] Email icon, Email Text Field, Toggle to make email preferred contact method
- [ ] Done Button (leads to /profile)

**Design:**
https://xd.adobe.com/view/27bc7fff-1845-449c-913a-4ecfb3c9461c-72ef/screen/baa8adab-e0e2-455f-8006-fb12b31df9d2
