### ISSUE TITLE
Account Creation - Step 3 (Wallet)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#595]
**Summary:**
As a new user I would like to be able to create a profile inside the DHO.

**Acceptance Criteria:**
- [ ] Headline
- [ ] Description Copy
- [ ] BTC icon, Address Field, Toggle to make BTC preferred payment method, Help text with link to documentation
- [ ] ETH icon, Address Field, Toggle to make BTC preferred payment method, Help text with link to documentation
- [ ] EOS icon, Memo Field, Address Field, Toggle to make BTC preferred payment method, Help text with link to documentation
- [ ] Next Button

**Design:**
https://xd.adobe.com/view/27bc7fff-1845-449c-913a-4ecfb3c9461c-72ef/screen/3e5fe52c-f34f-4089-a005-d0c2b57cd1de

**Comment by leonieherma1** [comment]
@arsenijesavic this step should not be mandatory. you can leave all 3 fields empty. Can you update that please?

**Comment by arsenijesavic** [comment]
> @arsenijesavic this step should not be mandatory. you can leave all 3 fields empty. Can you update that please?

@leonieherma1 Done ✅ ! https://github.com/hypha-dao/dho-web-client/commit/30e7274bcaa718157d7e77132ac68ccba294a723
