### ISSUE TITLE
Personal Sidebar - New Account

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#596]
**Summary:**
As a new DHO user I would like to see the personal sidebar with information that is relevant for me so I know what the next steps are.

**Acceptance Criteria:**

- [ ] For users that are accepted / enrolled in the DHO but just signed up, show the following sidebar:
- [ ] Placeholder Image (Initial on background)
- [ ] Username 
- [ ] Don't show (New Member)

Quick actions:

- [ ] Complete your profile (link to profile setup)
- [ ] Learn more about Hypha (link to /organization) page 
- [ ] Create your first proposal (link to /create)

**Design:**
https://xd.adobe.com/view/27bc7fff-1845-449c-913a-4ecfb3c9461c-72ef/screen/1dda7bde-a1b6-4cb0-898e-1cadba366796
