### ISSUE TITLE
Migrate queries to typed dgraph db - Member & Profile (L)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#626]
For support of multi-dho and performance reasons, we are migrating our dgraph queries to graphql queries using a typed interface. Support for this includes all the following steps:

- [x] Add client graphql library (vue-apollo) https://github.com/hypha-dao/dho-web-client/issues/520
- [x] Migrate proposal list query https://github.com/hypha-dao/dho-web-client/issues/520
- [x] Create proposal detail query https://github.com/hypha-dao/dho-web-client/issues/520
- [x] Create home page query (# active proposals, new members, etc) 
- [x] Create organization page query (circles?)

- [x] Migrate member list query 
- [x] Migrate profile page query
