### ISSUE TITLE
DHO Creation Wizard Flow - Step 3 (Token)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#866]
**Summary**
As a DHO user I would like to be able to create a new DHO with a few easy steps.

**Description:**
For the Beta Version we create DHOs manually via a command line and create the settings manually. For the public version we would like to have a "DHO Creation Wizard" that has 6 steps.

**Acceptance Criteria**

Step 3: 
**Utility Token:**
- [x] Headline: Utility Token
- [x] Copy: to be done

Name Field
- [x] Label: Name
- [x] Tooltip Copy: to be done
- [x] Placeholder copy: "max 7 characters uppercase A-Z"

Symbol Field
- [x] Label: Currency Symbol
- [x] Tooltip Copy: to be done
- [x] Placeholder copy: to be done (check with @Gerard097 how many characters this can have? I guess 3...and do we suggest to call it a certain style e.g. HUSD, HVOICE, etc....)

Contract Name @Gerard097 needed?

Number of Digits
- [x] Label: Number of Digits
- [x] Tooltip copy: to be done

Total Amount:
- [x] Label: Total Amount of Token
- [x] Tooltip Copy: to be done

Value (Dropdown):
- [x] Label: Value
- [x] Tooltip Copy: to be done
- [x] Placeholder Copy: to be done ($)
- [x] @Gerard097 should this be a dropdown or can be any value?

**Voice Token**
- [x] Headline: Voice Token
- [x] Copy: to be done

Name Field
- [x] Label: Name
- [x] Tooltip Copy: to be done
- [x] Placeholder copy: "max 7 characters uppercase A-Z"

Symbol Field
- [x] Label: Currency Symbol
- [x] Tooltip Copy: to be done
- [x] Placeholder copy: to be done 

Contract Name - needed?

Number of Digits
- [x] Label: Number of Digits
- [x] Tooltip copy: to be done

**Treasury Token**
- [x] Headline: Treasury Token
- [x] Copy: to be done

Name Field
- [x] Label: Name
- [x] Tooltip Copy: to be done
- [x] Placeholder copy: "max 7 characters uppercase A-Z"

Symbol Field
- [x] Label: Currency Symbol
- [x] Tooltip Copy: to be done
- [x] Placeholder copy: to be done 

Contract Name - needed?

Number of Digits
- [x] Label: Number of Digits
- [x] Tooltip copy: to be done

**Voice Decay**
- [x] Headline: Treasury Token
- [x] Copy: to be done
<img width="516" alt="image" src="https://user-images.githubusercontent.com/75991832/160466494-ceca7995-418f-4dc7-a819-16407f73d2af.png">

**Additional Token:**
- are we going to offer SEEDS integration @n13 @sceenius ?

**Design**
https://xd.adobe.com/view/27bc7fff-1845-449c-913a-4ecfb3c9461c-72ef/screen/68247d89-af41-4c31-9bb5-4471b837e93e/

**Comment by arsenijesavic** [comment]
@leonieherma1 I spoke with the @Gerard097, there is no need for the contract name, and name just the symbol and number of digits (expect for the utility token which has total amount and value (only in USD)). Symbol is 7 char max all uppercase.

**Comment by leonieherma1** [comment]
@arsenijesavic ok great, thanks
