### ISSUE TITLE
DHO Creation Wizard Flow - Step 4 (Team)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#868]
**Summary**
As a DHO user I would like to be able to create a new DHO with a few easy steps.

**Description:**
For the Beta Version we create DHOs manually via a command line and create the settings manually. For the public version we would like to have a "DHO Creation Wizard" that has 6 steps.

**Acceptance Criteria**

Step 4: 
- [x] Headline: Launch team
- [x] Copy: to be done

Name Field:
- [x] Label: Name
- [x] Placeholder copy: to be done

E-Mail Field:
- [x] Label: Email
- [x] Placeholder copy: to be done

Add more users
- [x] "Add more +"
- [x] Ability to add up to 10 more admins for that DHO

Button: 
- [x] Next Step

**Design**
https://xd.adobe.com/view/27bc7fff-1845-449c-913a-4ecfb3c9461c-72ef/screen/be7c5ff0-9fd6-4c50-a22f-4a642c4d15a7/
