### ISSUE TITLE
DHO Creation Wizard Flow - Step 6 (Compensation)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#869]
**Summary**
As a DHO user I would like to be able to create a new DHO with a few easy steps.

**Description:**
For the Beta Version we create DHOs manually via a command line and create the settings manually. For the public version we would like to have a "DHO Creation Wizard" that has 6 steps.

**Acceptance Criteria**

Step 6:
**Compensation**
- [x] Headline: Compensation
- [x] Copy: to be done
- [x] Utility Token: Icon, Multiplier, Field, Tooltip
- [x] Treasury Token: Icon, Multiplier, Field, Tooltip
- [x] Voice Token: Icon, Multiplier, Field, Tooltip

**Salary Bands:**
- [x] Headline: Salary Bands
- [x] Copy: to be done
- [x] Name, Value, Utility Token, Treasury Token, Voice Token
- [x] Add Band function
- [x] Remove Band function

Button:
- [x] Next step

**Design**
https://xd.adobe.com/view/27bc7fff-1845-449c-913a-4ecfb3c9461c-72ef/screen/2177766d-7188-48fd-898b-3adc41c3c99f/
