### ISSUE TITLE
DHO Creation Wizard Flow - Step 5 (Voting)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#870]
**Summary**
As a DHO user I would like to be able to create a new DHO with a few easy steps.

**Description:**
For the Beta Version we create DHOs manually via a command line and create the settings manually. For the public version we would like to have a "DHO Creation Wizard" that has 6 steps.

**Acceptance Criteria**

Step 5:
**Quorum**
- [x] Headline: Quorum
- [x] Copy: to be done
- [x] Slider
- [x] Field for number

**Unity**
- [x] Headline: Unity
- [x] Copy: to be done
- [x] Slider
- [x] Field for number

**Voting Duration**
- [x] Headline: Duration
- [x] Copy: to be done
- [x] Slider
- [x] Field for number

Button:
- [x] Next step

**Design**
We don't have this step in the designs but I think we can take the same designs as from the settings screen:

<img width="932" alt="image" src="https://user-images.githubusercontent.com/75991832/160250084-9fa5e955-5767-4821-b178-7353f6e6d584.png">
