### ISSUE TITLE
DHO Creation Wizard Flow - Step 7 (Design)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#871]
**Summary**
As a DHO user I would like to be able to create a new DHO with a few easy steps.

**Description:**
For the Beta Version we create DHOs manually via a command line and create the settings manually. For the public version we would like to have a "DHO Creation Wizard" that has 6 steps.

**Acceptance Criteria**

Step 6:
- [ ]  Headline: Design
- [ ] Copy: to be done

**Logo** 
- [ ] Upload Image
- [ ] Sizing (max MB?)

**Color Palette**
- [ ] Headline
- [ ] Copy
- [ ] Primary color picker
- [ ] Secondary color picker
- [ ] Components preview 

**Banners**
- [ ] Headline
- [ ] Copy
- [ ] Tab Navigation (Members, Homepage, Proposals, Organization)
- [ ] Background Colour
- [ ] Pattern
- [ ] Pattern colour
- [ ] or upload image (tooltip with image sizes 1270px x 300px max 1MB?)
- [ ] Banner Preview

**Slash Page:**
- [ ] Logo (Upload an image)
- [ ] Background Colour
- [ ] Pattern
- [ ] Pattern colour
- [ ] or upload image (tooltip with image sizes 1270px x 300px max 1MB?)
- [ ] Screen Preview

**Copy**

- [ ] Homepage Title (max 50 character), Homepage Description (max. 300 character)
- [ ] Member Page Title (max 50 character), Member Page Description (max. 300 character)
- [ ] Proposal Page Title (max 50 character), Proposal Page Description (max. 300 character)
- [ ] Organization Page Title (max 50 character), Organization Page Description (max. 300 character)

**Design**
In the XD file we use templates, I don't think they are 100% ready yet. Let's start with the customization we also use on the settings screen for now:

https://xd.adobe.com/view/6a16dbfb-56b7-4c05-8eb0-b8f4633050a2-3f45/screen/5874d328-e48f-4b52-9d56-656db168d1b0/?fullscreen

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/75991832/160250186-d38c8fca-8c33-4a94-8f12-423536cf1735.png">

**Comment by arsenijesavic** [comment]
@leonieherma1 If user clicks custom design the page should look like configuration page (which is the screen they you uploaded), and not like the current design (bottom part)?
<img width="288" alt="Screen Shot 2022-03-31 at 12 15 17" src="https://user-images.githubusercontent.com/7712798/161122733-8d8f2bc4-acc2-42fe-ada2-7a29ac17bfa1.png">

**Comment by leonieherma1** [comment]
@arsenijesavic if it is easier you can reuse the same as from configuratin page....

**Comment by leonieherma1** [comment]
@arsenijesavic we might kick out the part with the copy and have them do it later. Let's discuss with Joachim before you continue on it so you don't have double work
